FROM node:24.18.0-bookworm-slim

WORKDIR /app

RUN corepack enable \
    && corepack prepare pnpm@10.34.5 --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install --prod --frozen-lockfile --ignore-scripts \
    && pnpm rebuild @parcel/watcher @rocicorp/zero-sqlite3 esbuild protobufjs \
    && pnpm store prune

EXPOSE 4848

CMD ["./node_modules/.bin/zero-cache"]
