-- =============================================================================
-- 32_newsletter.sql - Newsletter subscriptions and Resend synchronization
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.newsletter_subscription (
  user_id UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  subscribed BOOLEAN NOT NULL DEFAULT true,
  sync_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (sync_status IN ('pending', 'synced', 'unsubscribed', 'error', 'deleted')),
  resend_contact_id TEXT UNIQUE,
  subscription_source TEXT NOT NULL DEFAULT 'automatic_signup',
  subscribed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  unsubscribed_at TIMESTAMPTZ,
  last_synced_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS newsletter_subscription_email_key
  ON public.newsletter_subscription (lower(email));

CREATE TABLE IF NOT EXISTS public.newsletter_sync_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID,
  operation TEXT NOT NULL CHECK (operation IN ('upsert', 'replace_email', 'delete')),
  email TEXT NOT NULL,
  previous_email TEXT,
  resend_contact_id TEXT,
  subscribed BOOLEAN NOT NULL DEFAULT true,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  attempt_count INTEGER NOT NULL DEFAULT 0,
  available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  locked_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS newsletter_sync_outbox_pending_idx
  ON public.newsletter_sync_outbox (available_at, id)
  WHERE status IN ('pending', 'failed');

CREATE TABLE IF NOT EXISTS public.resend_webhook_event (
  svix_id TEXT PRIMARY KEY,
  event_type TEXT NOT NULL,
  event_created_at TIMESTAMPTZ,
  payload JSONB NOT NULL,
  processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.newsletter_subscription ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.newsletter_sync_outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resend_webhook_event ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.newsletter_subscription FROM anon, authenticated;
REVOKE ALL ON TABLE public.newsletter_sync_outbox FROM anon, authenticated;
REVOKE ALL ON TABLE public.resend_webhook_event FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.newsletter_subscription TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.newsletter_sync_outbox TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.resend_webhook_event TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.newsletter_sync_outbox_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.enqueue_newsletter_subscription(
  target_user_id UUID,
  target_email TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  current_subscription public.newsletter_subscription%ROWTYPE;
BEGIN
  INSERT INTO public.newsletter_subscription (user_id, email)
  VALUES (target_user_id, target_email)
  ON CONFLICT (user_id) DO UPDATE
    SET email = excluded.email,
        updated_at = now()
  RETURNING * INTO current_subscription;

  INSERT INTO public.newsletter_sync_outbox (
    user_id,
    operation,
    email,
    resend_contact_id,
    subscribed
  ) VALUES (
    target_user_id,
    'upsert',
    target_email,
    current_subscription.resend_contact_id,
    current_subscription.subscribed
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.handle_auth_user_newsletter_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  current_subscription public.newsletter_subscription%ROWTYPE;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.email IS NOT NULL AND NEW.email_confirmed_at IS NOT NULL THEN
      PERFORM public.enqueue_newsletter_subscription(NEW.id, NEW.email);
    END IF;
    RETURN NEW;
  END IF;

  IF OLD.email_confirmed_at IS NULL
    AND NEW.email_confirmed_at IS NOT NULL
    AND NEW.email IS NOT NULL THEN
    PERFORM public.enqueue_newsletter_subscription(NEW.id, NEW.email);
    RETURN NEW;
  END IF;

  IF NEW.email_confirmed_at IS NOT NULL
    AND NEW.email IS NOT NULL
    AND NEW.email IS DISTINCT FROM OLD.email THEN
    SELECT * INTO current_subscription
      FROM public.newsletter_subscription
      WHERE user_id = NEW.id;

    IF FOUND THEN
      UPDATE public.newsletter_subscription
        SET email = NEW.email,
            resend_contact_id = NULL,
            sync_status = 'pending',
            last_error = NULL,
            updated_at = now()
        WHERE user_id = NEW.id;

      INSERT INTO public.newsletter_sync_outbox (
        user_id,
        operation,
        email,
        previous_email,
        resend_contact_id,
        subscribed
      ) VALUES (
        NEW.id,
        'replace_email',
        NEW.email,
        OLD.email,
        current_subscription.resend_contact_id,
        current_subscription.subscribed
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.handle_auth_user_newsletter_delete()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  current_subscription public.newsletter_subscription%ROWTYPE;
BEGIN
  SELECT * INTO current_subscription
    FROM public.newsletter_subscription
    WHERE user_id = OLD.id;

  IF FOUND THEN
    INSERT INTO public.newsletter_sync_outbox (
      user_id,
      operation,
      email,
      resend_contact_id,
      subscribed
    ) VALUES (
      OLD.id,
      'delete',
      current_subscription.email,
      current_subscription.resend_contact_id,
      current_subscription.subscribed
    );
  END IF;

  RETURN OLD;
END;
$$;

CREATE OR REPLACE TRIGGER on_auth_user_newsletter_changed
  AFTER INSERT OR UPDATE OF email, email_confirmed_at ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_auth_user_newsletter_change();

CREATE OR REPLACE TRIGGER on_auth_user_newsletter_deleted
  BEFORE DELETE ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_auth_user_newsletter_delete();

CREATE OR REPLACE FUNCTION public.claim_newsletter_sync_jobs(job_limit INTEGER DEFAULT 100)
RETURNS SETOF public.newsletter_sync_outbox
LANGUAGE sql
SECURITY DEFINER
SET search_path = ''
AS $$
  WITH candidates AS (
    SELECT id
    FROM public.newsletter_sync_outbox
    WHERE (
      status IN ('pending', 'failed') AND available_at <= now()
    ) OR (
      status = 'processing' AND locked_at < now() - INTERVAL '10 minutes'
    )
    ORDER BY id
    FOR UPDATE SKIP LOCKED
    LIMIT least(greatest(job_limit, 1), 100)
  )
  UPDATE public.newsletter_sync_outbox AS job
    SET status = 'processing',
        attempt_count = job.attempt_count + 1,
        locked_at = now(),
        updated_at = now()
    FROM candidates
    WHERE job.id = candidates.id
    RETURNING job.*;
$$;

REVOKE ALL ON FUNCTION public.enqueue_newsletter_subscription(UUID, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.handle_auth_user_newsletter_change() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.handle_auth_user_newsletter_delete() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.claim_newsletter_sync_jobs(INTEGER) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.claim_newsletter_sync_jobs(INTEGER) TO service_role;
