export const mechanics = [
  'run.mjs',
  'collect.ts',
  'measure.ts',
  'metrics.ts',
  'results.ts',
  'browser-navigation.ts',
  'journey-metrics.ts',
  'report.ts',
  'plan-artifacts.ts',
  'atomic-report.ts',
  'batches.ts',
  'required.ts',
  'isolation.mjs',
  'linux-runtime.mjs',
  'linux-browser.mjs',
  'api-timing.mjs',
  'fixture-check.ts',
  'sharding.ts',
  'execution.ts',
  'inventory.ts',
  'mutation-runtime.ts',
  'mutation-case-types.ts',
  'mutation-metrics.ts',
  'mutation-report.ts',
  'mutation-measure.ts',
  'mutation-observation.ts',
  'mutation-snapshot.ts',
  'mutation-request-completion.ts',
  'mutation-error-diagnostics.ts',
  'delivery-endpoint.mjs',
  'mutation-browser-metrics.ts',
  'mechanics.mjs',
];

// Only benchmark adapters are overlaid in application source. Business logic,
// schema, migrations and workload definitions continue to belong to each revision.
export const applicationMechanics = [
  'src/server/zero-mutation-diagnostics.ts',
  'src/server/zero-mutation-delivery.ts',
];
