import { table, string, number, json, type ReadonlyJSONValue } from '@rocicorp/zero';

export const changeRequest = table('change_request')
  .columns({
    id: string(),
    amendment_id: string(),
    user_id: string(),
    title: string().optional(),
    description: string().optional(),
    status: string().optional(),
    reason: string().optional(),
    source_type: string().optional(),
    source_id: string().optional(),
    source_title: string().optional(),
    change_type: string().optional(),
    original_text: string().optional(),
    new_text: string().optional(),
    original_properties: json<ReadonlyJSONValue>().optional(),
    new_properties: json<ReadonlyJSONValue>().optional(),
    changed_character_count: number(),
    votes_for: number(),
    votes_against: number(),
    votes_abstain: number(),
    voting_status: string(),
    voting_deadline: number().optional(),
    voting_majority_type: string().optional(),
    quorum_required: number().optional(),
    created_in_mode: string().optional(),
    resolved_in_mode: string().optional(),
    resolution_method: string().optional(),
    visibility_scope: string().optional(),
    created_at: number(),
    updated_at: number(),
  })
  .primaryKey('id');
