import type { StreetDesignObjectDefinition, StreetDesignObjectType } from '../types';

export const STREET_DESIGN_CURRENCY = 'EUR';
export const STREET_DESIGN_COST_CATALOG_VERSION = '2026-06-mvp';

export const streetDesignObjectRegistry = {
  tree: {
    type: 'tree',
    label: 'Baum',
    icon: 'TreePine',
    category: 'greenery',
    geometryKind: 'point',
    defaultProperties: {
      species: 'stadtbaum',
      height: 4,
      canopyDiameter: 3,
      spacing: 6,
    },
    propertySchema: [
      { key: 'species', label: 'Art', fieldType: 'text' },
      { key: 'height', label: 'Hoehe', fieldType: 'number', unit: 'm', min: 1, step: 0.5 },
      {
        key: 'canopyDiameter',
        label: 'Kronendurchmesser',
        fieldType: 'number',
        unit: 'm',
        min: 0.5,
        step: 0.5,
      },
      {
        key: 'spacing',
        label: 'Reihenabstand',
        fieldType: 'number',
        unit: 'm',
        min: 2,
        step: 0.5,
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 45000,
    renderKind: 'tree',
    toolMode: 'path',
    defaultWidth: 1.8,
    color: '#3f7d3b',
  },
  bush: {
    type: 'bush',
    label: 'Busch',
    icon: 'Shrub',
    category: 'greenery',
    geometryKind: 'point',
    defaultProperties: {
      species: 'strauch',
      diameter: 1.4,
      height: 1.2,
      spacing: 1.5,
    },
    propertySchema: [
      { key: 'species', label: 'Art', fieldType: 'text' },
      {
        key: 'diameter',
        label: 'Durchmesser',
        fieldType: 'number',
        unit: 'm',
        min: 0.3,
        step: 0.1,
      },
      { key: 'height', label: 'Hoehe', fieldType: 'number', unit: 'm', min: 0.2, step: 0.1 },
      {
        key: 'spacing',
        label: 'Reihenabstand',
        fieldType: 'number',
        unit: 'm',
        min: 0.4,
        step: 0.1,
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 8500,
    renderKind: 'bush',
    toolMode: 'path',
    defaultWidth: 1.2,
    color: '#5c8f46',
  },
  bank: {
    type: 'bank',
    label: 'Bank',
    icon: 'Armchair',
    category: 'furniture',
    geometryKind: 'point',
    defaultProperties: {
      material: 'holz',
      seats: 3,
    },
    propertySchema: [
      { key: 'material', label: 'Material', fieldType: 'text' },
      { key: 'seats', label: 'Sitzplaetze', fieldType: 'number', min: 1, step: 1 },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 120000,
    renderKind: 'bench',
    toolMode: 'point',
    color: '#8a6a42',
  },
  grass_strip: {
    type: 'grass_strip',
    label: 'Rasen',
    icon: 'Sprout',
    category: 'greenery',
    geometryKind: 'corridor',
    defaultProperties: {
      material: 'rasen',
      maintenance: 'standard',
    },
    propertySchema: [
      { key: 'material', label: 'Material', fieldType: 'text' },
      { key: 'maintenance', label: 'Pflege', fieldType: 'text' },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 1200,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 2,
    color: '#79a857',
  },
  flower_bed: {
    type: 'flower_bed',
    label: 'Blumenbeet',
    icon: 'Flower2',
    category: 'greenery',
    geometryKind: 'corridor',
    defaultProperties: {
      planting: 'staudenmix',
      maintenance: 'intensiv',
    },
    propertySchema: [
      { key: 'planting', label: 'Bepflanzung', fieldType: 'text' },
      { key: 'maintenance', label: 'Pflege', fieldType: 'text' },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 8000,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 1.6,
    color: '#c95f8a',
  },
  water_area: {
    type: 'water_area',
    label: 'Wasser',
    icon: 'Waves',
    category: 'water',
    geometryKind: 'corridor',
    defaultProperties: {
      waterType: 'retention',
      edge: 'naturnah',
    },
    propertySchema: [
      {
        key: 'waterType',
        label: 'Wassertyp',
        fieldType: 'select',
        options: [
          { label: 'Retention', value: 'retention' },
          { label: 'Teich', value: 'pond' },
          { label: 'Wasserlauf', value: 'stream' },
        ],
      },
      {
        key: 'edge',
        label: 'Ufer',
        fieldType: 'select',
        options: [
          { label: 'Naturnah', value: 'naturnah' },
          { label: 'Gefasst', value: 'gefasst' },
          { label: 'Sitzkante', value: 'sitzkante' },
        ],
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 6000,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 4,
    color: '#4f9ed9',
  },
  parking_area: {
    type: 'parking_area',
    label: 'Parkplatzflaeche',
    icon: 'ParkingSquare',
    category: 'mobility',
    geometryKind: 'corridor',
    defaultProperties: {
      parkingSpaces: 4,
      orientation: 'parallel',
    },
    propertySchema: [
      { key: 'parkingSpaces', label: 'Stellplaetze', fieldType: 'number', min: 1, step: 1 },
      {
        key: 'orientation',
        label: 'Ausrichtung',
        fieldType: 'select',
        options: [
          { label: 'Parallel', value: 'parallel' },
          { label: 'Schraeg', value: 'angled' },
          { label: 'Senkrecht', value: 'perpendicular' },
        ],
      },
    ],
    costRule: 'per_parking_space',
    suggestedUnitCostMinor: 350000,
    renderKind: 'parking',
    toolMode: 'drag-band',
    defaultWidth: 2.5,
    color: '#7f8da3',
  },
  street: {
    type: 'street',
    label: 'Strasse',
    icon: 'Route',
    category: 'street',
    geometryKind: 'corridor',
    defaultProperties: {
      surface: 'asphalt',
      lanes: 2,
    },
    propertySchema: [
      { key: 'surface', label: 'Belag', fieldType: 'text' },
      { key: 'lanes', label: 'Spuren', fieldType: 'number', min: 1, step: 1 },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 18000,
    renderKind: 'road',
    toolMode: 'path',
    defaultWidth: 6.5,
    color: '#4e565c',
  },
  car_lane: {
    type: 'car_lane',
    label: 'Fahrspur',
    icon: 'CarFront',
    category: 'street',
    geometryKind: 'corridor',
    defaultProperties: {
      direction: 'one_way',
      surface: 'asphalt',
    },
    propertySchema: [
      {
        key: 'direction',
        label: 'Richtung',
        fieldType: 'select',
        options: [
          { label: 'Eine Richtung', value: 'one_way' },
          { label: 'Beide Richtungen', value: 'two_way' },
        ],
      },
      { key: 'surface', label: 'Belag', fieldType: 'text' },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 13000,
    renderKind: 'lane',
    toolMode: 'path',
    defaultWidth: 3.25,
    color: '#586069',
  },
  bike_lane: {
    type: 'bike_lane',
    label: 'Radweg',
    icon: 'Bike',
    category: 'mobility',
    geometryKind: 'corridor',
    defaultProperties: {
      protection: 'markiert',
      surface: 'asphalt',
    },
    propertySchema: [
      { key: 'protection', label: 'Schutz', fieldType: 'text' },
      { key: 'surface', label: 'Belag', fieldType: 'text' },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 9000,
    renderKind: 'lane',
    toolMode: 'path',
    defaultWidth: 2,
    color: '#2f8f87',
  },
  sidewalk: {
    type: 'sidewalk',
    label: 'Gehweg',
    icon: 'Footprints',
    category: 'mobility',
    geometryKind: 'corridor',
    defaultProperties: {
      surface: 'pflaster',
      accessibility: true,
    },
    propertySchema: [
      { key: 'surface', label: 'Belag', fieldType: 'text' },
      { key: 'accessibility', label: 'Barrierearm', fieldType: 'boolean' },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 11000,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 2.4,
    color: '#c8bda7',
  },
  building: {
    type: 'building',
    label: 'Gebaeude',
    icon: 'Building2',
    category: 'building',
    geometryKind: 'corridor',
    defaultProperties: {
      height: 9,
      floors: 3,
      color: '#b6aa9b',
      use: 'mixed',
    },
    propertySchema: [
      { key: 'height', label: 'Hoehe', fieldType: 'number', unit: 'm', min: 1, step: 0.5 },
      { key: 'floors', label: 'Geschosse', fieldType: 'number', min: 1, step: 1 },
      {
        key: 'color',
        label: 'Farbe',
        fieldType: 'select',
        options: [
          { label: 'Sand', value: '#b6aa9b' },
          { label: 'Ziegel', value: '#b46b55' },
          { label: 'Schiefer', value: '#6f7a82' },
          { label: 'Blau', value: '#7aa0bd' },
          { label: 'Gruen', value: '#8ba77f' },
        ],
      },
      {
        key: 'use',
        label: 'Nutzung',
        fieldType: 'select',
        options: [
          { label: 'Gemischt', value: 'mixed' },
          { label: 'Wohnen', value: 'residential' },
          { label: 'Gewerbe', value: 'commercial' },
          { label: 'Oeffentlich', value: 'civic' },
        ],
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 250000,
    renderKind: 'building',
    toolMode: 'path',
    defaultWidth: 10,
    color: '#b6aa9b',
  },
} satisfies Record<StreetDesignObjectType, StreetDesignObjectDefinition>;

export const streetDesignObjectTypes = Object.keys(
  streetDesignObjectRegistry
) as StreetDesignObjectType[];

export function getStreetDesignObjectDefinition(
  type: StreetDesignObjectType
): StreetDesignObjectDefinition {
  return streetDesignObjectRegistry[type];
}
