import type {
  StreetDesignObjectDefinition,
  StreetDesignObjectType,
  StreetDesignPropertySchemaField,
} from '../types';
import { getStreetDesignBuildingUseColor } from './streetDesignBuildingUse';
import { streetDesignPropertyOptions } from './streetDesignVariantCatalog';

export const STREET_DESIGN_CURRENCY = 'EUR';
export const STREET_DESIGN_COST_CATALOG_VERSION = '2026-06-mvp';

const streetDesignElevationPropertyFields: StreetDesignPropertySchemaField[] = [
  {
    key: 'layerIndex',
    labelKey: 'features.amendments.streetscape.objects.common.properties.layerIndex',
    fieldType: 'number',
    step: 1,
  },
  {
    key: 'deckElevationMeters',
    labelKey: 'features.amendments.streetscape.objects.common.properties.deckElevationMeters',
    fieldType: 'number',
    unit: 'm',
    step: 0.1,
  },
  {
    key: 'structureKind',
    labelKey: 'features.amendments.streetscape.objects.common.properties.structureKind',
    fieldType: 'combobox',
    options: streetDesignPropertyOptions.level,
  },
];

export const streetDesignObjectRegistry = {
  tree: {
    type: 'tree',
    labelKey: 'features.amendments.streetscape.objects.tree.label',
    icon: 'TreePine',
    category: 'greenery',
    geometryKind: 'point',
    defaultProperties: {
      species: 'stadtbaum',
      height: 4,
      canopyDiameter: 3,
      spacing: 6,
    },
    propertySchema: [
      {
        key: 'species',
        labelKey: 'features.amendments.streetscape.objects.tree.properties.species',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.species,
      },
      {
        key: 'height',
        labelKey: 'features.amendments.streetscape.objects.common.properties.height',
        fieldType: 'number',
        unit: 'm',
        min: 1,
        step: 0.5,
      },
      {
        key: 'canopyDiameter',
        labelKey: 'features.amendments.streetscape.objects.tree.properties.canopyDiameter',
        fieldType: 'number',
        unit: 'm',
        min: 0.5,
        step: 0.5,
      },
      {
        key: 'spacing',
        labelKey: 'features.amendments.streetscape.objects.common.properties.spacing',
        fieldType: 'number',
        unit: 'm',
        min: 2,
        step: 0.5,
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 45000,
    renderKind: 'tree',
    toolMode: 'path',
    defaultWidth: 1.8,
    color: '#3f7d3b',
  },
  bush: {
    type: 'bush',
    labelKey: 'features.amendments.streetscape.objects.bush.label',
    icon: 'Shrub',
    category: 'greenery',
    geometryKind: 'point',
    defaultProperties: {
      species: 'strauch',
      diameter: 1.4,
      height: 1.2,
      spacing: 1.5,
    },
    propertySchema: [
      {
        key: 'species',
        labelKey: 'features.amendments.streetscape.objects.bush.properties.species',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.species,
      },
      {
        key: 'diameter',
        labelKey: 'features.amendments.streetscape.objects.bush.properties.diameter',
        fieldType: 'number',
        unit: 'm',
        min: 0.3,
        step: 0.1,
      },
      {
        key: 'height',
        labelKey: 'features.amendments.streetscape.objects.common.properties.height',
        fieldType: 'number',
        unit: 'm',
        min: 0.2,
        step: 0.1,
      },
      {
        key: 'spacing',
        labelKey: 'features.amendments.streetscape.objects.common.properties.spacing',
        fieldType: 'number',
        unit: 'm',
        min: 0.4,
        step: 0.1,
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 8500,
    renderKind: 'bush',
    toolMode: 'path',
    defaultWidth: 1.2,
    color: '#5c8f46',
  },
  bank: {
    type: 'bank',
    labelKey: 'features.amendments.streetscape.objects.bank.label',
    icon: 'Armchair',
    category: 'furniture',
    geometryKind: 'point',
    defaultProperties: {
      material: 'holz',
      seats: 3,
    },
    propertySchema: [
      {
        key: 'material',
        labelKey: 'features.amendments.streetscape.objects.common.properties.material',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.material,
      },
      {
        key: 'seats',
        labelKey: 'features.amendments.streetscape.objects.bank.properties.seats',
        fieldType: 'number',
        min: 1,
        step: 1,
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 120000,
    renderKind: 'bench',
    toolMode: 'point',
    color: '#8a6a42',
  },
  grass_strip: {
    type: 'grass_strip',
    labelKey: 'features.amendments.streetscape.objects.grassStrip.label',
    icon: 'Sprout',
    category: 'greenery',
    geometryKind: 'corridor',
    defaultProperties: {
      material: 'rasen',
      maintenance: 'standard',
    },
    propertySchema: [
      {
        key: 'material',
        labelKey: 'features.amendments.streetscape.objects.common.properties.material',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.surface,
      },
      {
        key: 'maintenance',
        labelKey: 'features.amendments.streetscape.objects.common.properties.maintenance',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.maintenance,
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 1200,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 2,
    color: '#79a857',
  },
  flower_bed: {
    type: 'flower_bed',
    labelKey: 'features.amendments.streetscape.objects.flowerBed.label',
    icon: 'Flower2',
    category: 'greenery',
    geometryKind: 'corridor',
    defaultProperties: {
      planting: 'staudenmix',
      maintenance: 'intensiv',
    },
    propertySchema: [
      {
        key: 'planting',
        labelKey: 'features.amendments.streetscape.objects.flowerBed.properties.planting',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.planting,
      },
      {
        key: 'maintenance',
        labelKey: 'features.amendments.streetscape.objects.common.properties.maintenance',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.maintenance,
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 8000,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 1.6,
    color: '#c95f8a',
  },
  scrub_area: {
    type: 'scrub_area',
    labelKey: 'features.amendments.streetscape.objects.scrubArea.label',
    icon: 'Shrub',
    category: 'greenery',
    geometryKind: 'corridor',
    defaultProperties: {
      planting: 'scrub',
      maintenance: 'extensiv',
    },
    propertySchema: [
      {
        key: 'planting',
        labelKey: 'features.amendments.streetscape.objects.common.properties.planting',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.planting,
      },
      {
        key: 'maintenance',
        labelKey: 'features.amendments.streetscape.objects.common.properties.maintenance',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.maintenance,
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 3500,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 3,
    color: '#587c49',
  },
  heath_area: {
    type: 'heath_area',
    labelKey: 'features.amendments.streetscape.objects.heathArea.label',
    icon: 'Sprout',
    category: 'greenery',
    geometryKind: 'corridor',
    defaultProperties: {
      planting: 'heide',
      maintenance: 'extensiv',
    },
    propertySchema: [
      {
        key: 'planting',
        labelKey: 'features.amendments.streetscape.objects.common.properties.planting',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.planting,
      },
      {
        key: 'maintenance',
        labelKey: 'features.amendments.streetscape.objects.common.properties.maintenance',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.maintenance,
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 2800,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 3,
    color: '#8f7f55',
  },
  orchard_area: {
    type: 'orchard_area',
    labelKey: 'features.amendments.streetscape.objects.orchardArea.label',
    icon: 'TreePine',
    category: 'greenery',
    geometryKind: 'corridor',
    defaultProperties: {
      crop: 'fruit',
      rowSpacing: 5,
    },
    propertySchema: [
      {
        key: 'crop',
        labelKey: 'features.amendments.streetscape.objects.common.properties.crop',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.crop,
      },
      {
        key: 'rowSpacing',
        labelKey: 'features.amendments.streetscape.objects.common.properties.spacing',
        fieldType: 'number',
        unit: 'm',
        min: 1,
        step: 0.5,
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 4200,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 6,
    color: '#6f8d45',
  },
  vineyard_area: {
    type: 'vineyard_area',
    labelKey: 'features.amendments.streetscape.objects.vineyardArea.label',
    icon: 'Rows3',
    category: 'greenery',
    geometryKind: 'corridor',
    defaultProperties: {
      crop: 'grapes',
      rowSpacing: 2,
    },
    propertySchema: [
      {
        key: 'crop',
        labelKey: 'features.amendments.streetscape.objects.common.properties.crop',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.crop,
      },
      {
        key: 'rowSpacing',
        labelKey: 'features.amendments.streetscape.objects.common.properties.spacing',
        fieldType: 'number',
        unit: 'm',
        min: 1,
        step: 0.25,
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 3800,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 4,
    color: '#78935f',
  },
  water_area: {
    type: 'water_area',
    labelKey: 'features.amendments.streetscape.objects.waterArea.label',
    icon: 'Waves',
    category: 'water',
    geometryKind: 'corridor',
    defaultProperties: {
      waterType: 'retention',
      edge: 'naturnah',
      intermittent: false,
    },
    propertySchema: [
      {
        key: 'waterType',
        labelKey: 'features.amendments.streetscape.objects.waterArea.properties.waterType.label',
        fieldType: 'select',
        options: [
          {
            labelKey:
              'features.amendments.streetscape.objects.waterArea.properties.waterType.options.retention',
            value: 'retention',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.waterArea.properties.waterType.options.pond',
            value: 'pond',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.waterArea.properties.waterType.options.stream',
            value: 'stream',
          },
        ],
      },
      {
        key: 'edge',
        labelKey: 'features.amendments.streetscape.objects.waterArea.properties.edge.label',
        fieldType: 'select',
        options: [
          {
            labelKey:
              'features.amendments.streetscape.objects.waterArea.properties.edge.options.natural',
            value: 'naturnah',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.waterArea.properties.edge.options.framed',
            value: 'gefasst',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.waterArea.properties.edge.options.seatingEdge',
            value: 'sitzkante',
          },
        ],
      },
      {
        key: 'intermittent',
        labelKey: 'features.amendments.streetscape.objects.waterArea.properties.intermittent',
        fieldType: 'boolean',
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 6000,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 4,
    color: '#4f9ed9',
  },
  wetland_area: {
    type: 'wetland_area',
    labelKey: 'features.amendments.streetscape.objects.wetlandArea.label',
    icon: 'Waves',
    category: 'water',
    geometryKind: 'corridor',
    defaultProperties: {
      wetlandType: 'reedbed',
      intermittent: false,
    },
    propertySchema: [
      {
        key: 'wetlandType',
        labelKey: 'features.amendments.streetscape.objects.wetlandArea.properties.wetlandType',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.wetlandType,
      },
      {
        key: 'intermittent',
        labelKey: 'features.amendments.streetscape.objects.waterArea.properties.intermittent',
        fieldType: 'boolean',
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 4500,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 5,
    color: '#6f8f78',
  },
  parking_area: {
    type: 'parking_area',
    labelKey: 'features.amendments.streetscape.objects.parkingArea.label',
    icon: 'ParkingSquare',
    category: 'mobility',
    geometryKind: 'corridor',
    defaultProperties: {
      parkingSpaces: 4,
      orientation: 'parallel',
    },
    propertySchema: [
      {
        key: 'parkingSpaces',
        labelKey: 'features.amendments.streetscape.objects.parkingArea.properties.parkingSpaces',
        fieldType: 'number',
        min: 1,
        step: 1,
      },
      {
        key: 'orientation',
        labelKey:
          'features.amendments.streetscape.objects.parkingArea.properties.orientation.label',
        fieldType: 'select',
        options: [
          {
            labelKey:
              'features.amendments.streetscape.objects.parkingArea.properties.orientation.options.parallel',
            value: 'parallel',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.parkingArea.properties.orientation.options.angled',
            value: 'angled',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.parkingArea.properties.orientation.options.perpendicular',
            value: 'perpendicular',
          },
        ],
      },
    ],
    costRule: 'per_parking_space',
    suggestedUnitCostMinor: 350000,
    renderKind: 'parking',
    toolMode: 'drag-band',
    defaultWidth: 2.5,
    color: '#7f8da3',
  },
  loading_zone: {
    type: 'loading_zone',
    labelKey: 'features.amendments.streetscape.objects.loadingZone.label',
    icon: 'ParkingSquare',
    category: 'mobility',
    geometryKind: 'corridor',
    defaultProperties: {
      restriction: 'loading_only',
      lengthMeters: 12,
    },
    propertySchema: [
      {
        key: 'restriction',
        labelKey: 'features.amendments.streetscape.objects.loadingZone.properties.restriction',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.restriction,
      },
      {
        key: 'lengthMeters',
        labelKey: 'features.amendments.streetscape.objects.loadingZone.properties.lengthMeters',
        fieldType: 'number',
        unit: 'm',
        min: 2,
        step: 1,
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 9000,
    renderKind: 'parking',
    toolMode: 'drag-band',
    defaultWidth: 2.5,
    color: '#9a7a45',
  },
  street: {
    type: 'street',
    labelKey: 'features.amendments.streetscape.objects.street.label',
    icon: 'Route',
    category: 'street',
    geometryKind: 'corridor',
    defaultProperties: {
      surface: 'asphalt',
      lanes: 2,
      roadClass: 'residential',
      access: 'public',
      level: 'surface',
      status: 'open',
      layerIndex: 0,
      deckElevationMeters: 0,
      structureKind: 'surface',
    },
    propertySchema: [
      {
        key: 'surface',
        labelKey: 'features.amendments.streetscape.objects.common.properties.surface',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.surface,
      },
      {
        key: 'lanes',
        labelKey: 'features.amendments.streetscape.objects.street.properties.lanes',
        fieldType: 'number',
        min: 1,
        step: 1,
      },
      {
        key: 'roadClass',
        labelKey: 'features.amendments.streetscape.objects.street.properties.roadClass',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.roadClass,
      },
      {
        key: 'access',
        labelKey: 'features.amendments.streetscape.objects.common.properties.access',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.access,
      },
      {
        key: 'level',
        labelKey: 'features.amendments.streetscape.objects.common.properties.level',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.level,
      },
      {
        key: 'status',
        labelKey: 'features.amendments.streetscape.objects.common.properties.status',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.status,
      },
      ...streetDesignElevationPropertyFields,
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 18000,
    renderKind: 'road',
    toolMode: 'path',
    defaultWidth: 6.5,
    color: '#4e565c',
  },
  car_lane: {
    type: 'car_lane',
    labelKey: 'features.amendments.streetscape.objects.carLane.label',
    icon: 'CarFront',
    category: 'street',
    geometryKind: 'corridor',
    defaultProperties: {
      direction: 'one_way',
      surface: 'asphalt',
      access: 'public',
      level: 'surface',
      status: 'open',
      layerIndex: 0,
      deckElevationMeters: 0,
      structureKind: 'surface',
    },
    propertySchema: [
      {
        key: 'direction',
        labelKey: 'features.amendments.streetscape.objects.carLane.properties.direction.label',
        fieldType: 'select',
        options: [
          {
            labelKey:
              'features.amendments.streetscape.objects.carLane.properties.direction.options.oneWay',
            value: 'one_way',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.carLane.properties.direction.options.twoWay',
            value: 'two_way',
          },
        ],
      },
      {
        key: 'surface',
        labelKey: 'features.amendments.streetscape.objects.common.properties.surface',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.surface,
      },
      {
        key: 'access',
        labelKey: 'features.amendments.streetscape.objects.common.properties.access',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.access,
      },
      {
        key: 'level',
        labelKey: 'features.amendments.streetscape.objects.common.properties.level',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.level,
      },
      {
        key: 'status',
        labelKey: 'features.amendments.streetscape.objects.common.properties.status',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.status,
      },
      ...streetDesignElevationPropertyFields,
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 13000,
    renderKind: 'lane',
    toolMode: 'path',
    defaultWidth: 3.25,
    color: '#586069',
  },
  bike_lane: {
    type: 'bike_lane',
    labelKey: 'features.amendments.streetscape.objects.bikeLane.label',
    icon: 'Bike',
    category: 'mobility',
    geometryKind: 'corridor',
    defaultProperties: {
      protection: 'painted',
      surface: 'asphalt',
      layerIndex: 0,
      deckElevationMeters: 0,
      structureKind: 'surface',
    },
    propertySchema: [
      {
        key: 'protection',
        labelKey: 'features.amendments.streetscape.objects.bikeLane.properties.protection',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.protection,
      },
      {
        key: 'surface',
        labelKey: 'features.amendments.streetscape.objects.common.properties.surface',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.surface,
      },
      ...streetDesignElevationPropertyFields,
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 9000,
    renderKind: 'lane',
    toolMode: 'path',
    defaultWidth: 2,
    color: '#2f8f87',
  },
  sidewalk: {
    type: 'sidewalk',
    labelKey: 'features.amendments.streetscape.objects.sidewalk.label',
    icon: 'Footprints',
    category: 'mobility',
    geometryKind: 'corridor',
    defaultProperties: {
      surface: 'pflaster',
      accessibility: true,
      pathType: 'sidewalk',
      layerIndex: 0,
      deckElevationMeters: 0,
      structureKind: 'surface',
    },
    propertySchema: [
      {
        key: 'surface',
        labelKey: 'features.amendments.streetscape.objects.common.properties.surface',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.surface,
      },
      {
        key: 'accessibility',
        labelKey: 'features.amendments.streetscape.objects.sidewalk.properties.accessibility',
        fieldType: 'boolean',
      },
      {
        key: 'pathType',
        labelKey: 'features.amendments.streetscape.objects.sidewalk.properties.pathType',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.pathType,
      },
      ...streetDesignElevationPropertyFields,
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 11000,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 2.4,
    color: '#c8bda7',
  },
  building: {
    type: 'building',
    labelKey: 'features.amendments.streetscape.objects.building.label',
    icon: 'Building2',
    category: 'building',
    geometryKind: 'corridor',
    defaultProperties: {
      height: 9,
      floors: 3,
      use: 'mixed',
      semanticUse: 'mixed',
      color: getStreetDesignBuildingUseColor('mixed'),
      renderColor: getStreetDesignBuildingUseColor('mixed'),
    },
    propertySchema: [
      {
        key: 'height',
        labelKey: 'features.amendments.streetscape.objects.common.properties.height',
        fieldType: 'number',
        unit: 'm',
        min: 1,
        step: 0.5,
      },
      {
        key: 'floors',
        labelKey: 'features.amendments.streetscape.objects.building.properties.floors',
        fieldType: 'number',
        min: 1,
        step: 1,
      },
      {
        key: 'color',
        labelKey: 'features.amendments.streetscape.objects.building.properties.color.label',
        fieldType: 'select',
        options: [
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.color.options.sand',
            value: '#b6aa9b',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.color.options.residential',
            value: '#c8bda7',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.color.options.brick',
            value: '#b46b55',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.color.options.slate',
            value: '#6f7a82',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.color.options.blue',
            value: '#7aa0bd',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.color.options.green',
            value: '#8ba77f',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.color.options.hospitality',
            value: '#c9a45c',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.color.options.industrial',
            value: '#6b7280',
          },
        ],
      },
      {
        key: 'use',
        labelKey: 'features.amendments.streetscape.objects.building.properties.use.label',
        fieldType: 'select',
        options: [
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.use.options.mixed',
            value: 'mixed',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.use.options.residential',
            value: 'residential',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.use.options.commercial',
            value: 'commercial',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.use.options.retail',
            value: 'retail',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.use.options.office',
            value: 'office',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.use.options.hospitality',
            value: 'hospitality',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.use.options.industrial',
            value: 'industrial',
          },
          {
            labelKey:
              'features.amendments.streetscape.objects.building.properties.use.options.civic',
            value: 'civic',
          },
        ],
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 250000,
    renderKind: 'building',
    toolMode: 'path',
    defaultWidth: 10,
    color: '#b6aa9b',
  },
  street_lamp: {
    type: 'street_lamp',
    labelKey: 'features.amendments.streetscape.objects.streetLamp.label',
    icon: 'Lamp',
    category: 'furniture',
    geometryKind: 'point',
    defaultProperties: { height: 5, material: 'stahl' },
    propertySchema: [
      {
        key: 'height',
        labelKey: 'features.amendments.streetscape.objects.common.properties.height',
        fieldType: 'number',
        unit: 'm',
        min: 2,
        step: 0.5,
      },
      {
        key: 'material',
        labelKey: 'features.amendments.streetscape.objects.common.properties.material',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.material,
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 180000,
    renderKind: 'street_furniture',
    toolMode: 'point',
    color: '#f6d365',
  },
  hydrant: {
    type: 'hydrant',
    labelKey: 'features.amendments.streetscape.objects.hydrant.label',
    icon: 'Droplet',
    category: 'furniture',
    geometryKind: 'point',
    defaultProperties: { material: 'metall' },
    propertySchema: [
      {
        key: 'material',
        labelKey: 'features.amendments.streetscape.objects.common.properties.material',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.material,
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 90000,
    renderKind: 'utility',
    toolMode: 'point',
    color: '#c2410c',
  },
  bicycle_parking: {
    type: 'bicycle_parking',
    labelKey: 'features.amendments.streetscape.objects.bicycleParking.label',
    icon: 'Bike',
    category: 'mobility',
    geometryKind: 'corridor',
    defaultProperties: { stands: 6, material: 'stahl' },
    propertySchema: [
      {
        key: 'stands',
        labelKey: 'features.amendments.streetscape.objects.bicycleParking.properties.stands',
        fieldType: 'number',
        min: 1,
        step: 1,
      },
      {
        key: 'material',
        labelKey: 'features.amendments.streetscape.objects.common.properties.material',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.material,
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 18000,
    renderKind: 'street_furniture',
    toolMode: 'path',
    defaultWidth: 2,
    color: '#64748b',
  },
  bollard: {
    type: 'bollard',
    labelKey: 'features.amendments.streetscape.objects.bollard.label',
    icon: 'Circle',
    category: 'furniture',
    geometryKind: 'point',
    defaultProperties: { material: 'metall', height: 0.9 },
    propertySchema: [
      {
        key: 'height',
        labelKey: 'features.amendments.streetscape.objects.common.properties.height',
        fieldType: 'number',
        unit: 'm',
        min: 0.3,
        step: 0.1,
      },
      {
        key: 'material',
        labelKey: 'features.amendments.streetscape.objects.common.properties.material',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.material,
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 35000,
    renderKind: 'barrier',
    toolMode: 'point',
    color: '#475569',
  },
  gate: {
    type: 'gate',
    labelKey: 'features.amendments.streetscape.objects.gate.label',
    icon: 'DoorOpen',
    category: 'furniture',
    geometryKind: 'point',
    defaultProperties: { width: 2.4, material: 'metall' },
    propertySchema: [
      {
        key: 'width',
        labelKey: 'features.amendments.streetscape.inspector.width',
        fieldType: 'number',
        unit: 'm',
        min: 0.6,
        step: 0.2,
      },
      {
        key: 'material',
        labelKey: 'features.amendments.streetscape.objects.common.properties.material',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.material,
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 220000,
    renderKind: 'barrier',
    toolMode: 'point',
    color: '#334155',
  },
  fence: {
    type: 'fence',
    labelKey: 'features.amendments.streetscape.objects.fence.label',
    icon: 'Rows3',
    category: 'furniture',
    geometryKind: 'corridor',
    defaultProperties: { height: 1.2, material: 'metall' },
    propertySchema: [
      {
        key: 'height',
        labelKey: 'features.amendments.streetscape.objects.common.properties.height',
        fieldType: 'number',
        unit: 'm',
        min: 0.4,
        step: 0.1,
      },
      {
        key: 'material',
        labelKey: 'features.amendments.streetscape.objects.common.properties.material',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.material,
      },
    ],
    costRule: 'per_meter',
    suggestedUnitCostMinor: 25000,
    renderKind: 'barrier',
    toolMode: 'path',
    defaultWidth: 0.4,
    color: '#64748b',
  },
  wall: {
    type: 'wall',
    labelKey: 'features.amendments.streetscape.objects.wall.label',
    icon: 'BrickWall',
    category: 'furniture',
    geometryKind: 'corridor',
    defaultProperties: { height: 1.1, material: 'stein' },
    propertySchema: [
      {
        key: 'height',
        labelKey: 'features.amendments.streetscape.objects.common.properties.height',
        fieldType: 'number',
        unit: 'm',
        min: 0.3,
        step: 0.1,
      },
      {
        key: 'material',
        labelKey: 'features.amendments.streetscape.objects.common.properties.material',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.material,
      },
    ],
    costRule: 'per_meter',
    suggestedUnitCostMinor: 65000,
    renderKind: 'barrier',
    toolMode: 'path',
    defaultWidth: 0.5,
    color: '#8a8178',
  },
  traffic_signal: {
    type: 'traffic_signal',
    labelKey: 'features.amendments.streetscape.objects.trafficSignal.label',
    icon: 'TrafficCone',
    category: 'street',
    geometryKind: 'point',
    defaultProperties: { signalType: 'vehicle' },
    propertySchema: [
      {
        key: 'signalType',
        labelKey: 'features.amendments.streetscape.objects.trafficSignal.properties.signalType',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.signalType,
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 280000,
    renderKind: 'traffic',
    toolMode: 'point',
    color: '#1f2937',
  },
  crossing: {
    type: 'crossing',
    labelKey: 'features.amendments.streetscape.objects.crossing.label',
    icon: 'Footprints',
    category: 'mobility',
    geometryKind: 'corridor',
    defaultProperties: { crossingType: 'zebra' },
    propertySchema: [
      {
        key: 'crossingType',
        labelKey: 'features.amendments.streetscape.objects.crossing.properties.crossingType',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.crossingType,
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 7000,
    renderKind: 'traffic',
    toolMode: 'path',
    defaultWidth: 3,
    color: '#f8fafc',
  },
  traffic_calming: {
    type: 'traffic_calming',
    labelKey: 'features.amendments.streetscape.objects.trafficCalming.label',
    icon: 'Triangle',
    category: 'street',
    geometryKind: 'corridor',
    defaultProperties: { calmingType: 'table' },
    propertySchema: [
      {
        key: 'calmingType',
        labelKey: 'features.amendments.streetscape.objects.trafficCalming.properties.calmingType',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.calmingType,
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 16000,
    renderKind: 'traffic',
    toolMode: 'path',
    defaultWidth: 2.5,
    color: '#d97706',
  },
  bus_stop: {
    type: 'bus_stop',
    labelKey: 'features.amendments.streetscape.objects.busStop.label',
    icon: 'Bus',
    category: 'mobility',
    geometryKind: 'point',
    defaultProperties: { shelter: true },
    propertySchema: [
      {
        key: 'shelter',
        labelKey: 'features.amendments.streetscape.objects.busStop.properties.shelter',
        fieldType: 'boolean',
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 650000,
    renderKind: 'transit',
    toolMode: 'point',
    color: '#2563eb',
  },
  rail_track: {
    type: 'rail_track',
    labelKey: 'features.amendments.streetscape.objects.railTrack.label',
    icon: 'RailSymbol',
    category: 'street',
    geometryKind: 'corridor',
    defaultProperties: {
      railType: 'tram',
      level: 'surface',
      layerIndex: 0,
      deckElevationMeters: 0,
      structureKind: 'surface',
    },
    propertySchema: [
      {
        key: 'railType',
        labelKey: 'features.amendments.streetscape.objects.railTrack.properties.railType',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.railType,
      },
      {
        key: 'level',
        labelKey: 'features.amendments.streetscape.objects.common.properties.level',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.level,
      },
      ...streetDesignElevationPropertyFields,
    ],
    costRule: 'per_meter',
    suggestedUnitCostMinor: 180000,
    renderKind: 'rail',
    toolMode: 'path',
    defaultWidth: 1.6,
    color: '#475569',
  },
  station_platform: {
    type: 'station_platform',
    labelKey: 'features.amendments.streetscape.objects.stationPlatform.label',
    icon: 'Route',
    category: 'mobility',
    geometryKind: 'corridor',
    defaultProperties: { platformType: 'tram_stop', shelter: true },
    propertySchema: [
      {
        key: 'platformType',
        labelKey: 'features.amendments.streetscape.objects.stationPlatform.properties.platformType',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.platformType,
      },
      {
        key: 'shelter',
        labelKey: 'features.amendments.streetscape.objects.busStop.properties.shelter',
        fieldType: 'boolean',
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 32000,
    renderKind: 'transit',
    toolMode: 'path',
    defaultWidth: 3,
    color: '#60a5fa',
  },
  playground: {
    type: 'playground',
    labelKey: 'features.amendments.streetscape.objects.playground.label',
    icon: 'FerrisWheel',
    category: 'furniture',
    geometryKind: 'corridor',
    defaultProperties: { surface: 'fallschutz', equipment: 'mixed' },
    propertySchema: [
      {
        key: 'surface',
        labelKey: 'features.amendments.streetscape.objects.common.properties.surface',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.surface,
      },
      {
        key: 'equipment',
        labelKey: 'features.amendments.streetscape.objects.playground.properties.equipment',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.equipment,
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 45000,
    renderKind: 'playground',
    toolMode: 'path',
    defaultWidth: 6,
    color: '#d6a23f',
  },
  sports_pitch: {
    type: 'sports_pitch',
    labelKey: 'features.amendments.streetscape.objects.sportsPitch.label',
    icon: 'Goal',
    category: 'furniture',
    geometryKind: 'corridor',
    defaultProperties: { sport: 'multi', surface: 'kunststoff' },
    propertySchema: [
      {
        key: 'sport',
        labelKey: 'features.amendments.streetscape.objects.sportsPitch.properties.sport',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.sport,
      },
      {
        key: 'surface',
        labelKey: 'features.amendments.streetscape.objects.common.properties.surface',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.surface,
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 22000,
    renderKind: 'sports',
    toolMode: 'path',
    defaultWidth: 8,
    color: '#5f9f65',
  },
  waste_bin: {
    type: 'waste_bin',
    labelKey: 'features.amendments.streetscape.objects.wasteBin.label',
    icon: 'Trash2',
    category: 'furniture',
    geometryKind: 'point',
    defaultProperties: { capacity: 50 },
    propertySchema: [
      {
        key: 'capacity',
        labelKey: 'features.amendments.streetscape.objects.wasteBin.properties.capacity',
        fieldType: 'number',
        min: 10,
        step: 10,
        unit: 'l',
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 45000,
    renderKind: 'utility',
    toolMode: 'point',
    color: '#3f3f46',
  },
  recycling_container: {
    type: 'recycling_container',
    labelKey: 'features.amendments.streetscape.objects.recyclingContainer.label',
    icon: 'Recycle',
    category: 'furniture',
    geometryKind: 'point',
    defaultProperties: { material: 'glas/papier' },
    propertySchema: [
      {
        key: 'material',
        labelKey: 'features.amendments.streetscape.objects.common.properties.material',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.material,
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 140000,
    renderKind: 'utility',
    toolMode: 'point',
    color: '#15803d',
  },
  post_box: {
    type: 'post_box',
    labelKey: 'features.amendments.streetscape.objects.postBox.label',
    icon: 'Mailbox',
    category: 'furniture',
    geometryKind: 'point',
    defaultProperties: { operator: 'post' },
    propertySchema: [
      {
        key: 'operator',
        labelKey: 'features.amendments.streetscape.objects.postBox.properties.operator',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.operator,
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 75000,
    renderKind: 'utility',
    toolMode: 'point',
    color: '#facc15',
  },
  fountain: {
    type: 'fountain',
    labelKey: 'features.amendments.streetscape.objects.fountain.label',
    icon: 'Waves',
    category: 'water',
    geometryKind: 'point',
    defaultProperties: { waterType: 'drinking' },
    propertySchema: [
      {
        key: 'waterType',
        labelKey: 'features.amendments.streetscape.objects.waterArea.properties.waterType.label',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.fountainWaterType,
      },
    ],
    costRule: 'per_item',
    suggestedUnitCostMinor: 220000,
    renderKind: 'utility',
    toolMode: 'point',
    color: '#38bdf8',
  },
  stairs: {
    type: 'stairs',
    labelKey: 'features.amendments.streetscape.objects.stairs.label',
    icon: 'Footprints',
    category: 'mobility',
    geometryKind: 'corridor',
    defaultProperties: {
      steps: 6,
      material: 'beton',
      incline: 'up',
      deckElevationMeters: 1,
    },
    propertySchema: [
      {
        key: 'steps',
        labelKey: 'features.amendments.streetscape.objects.stairs.properties.steps',
        fieldType: 'number',
        min: 1,
        step: 1,
      },
      {
        key: 'material',
        labelKey: 'features.amendments.streetscape.objects.common.properties.material',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.material,
      },
      {
        key: 'incline',
        labelKey: 'features.amendments.streetscape.objects.common.properties.incline',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.incline,
      },
      {
        key: 'deckElevationMeters',
        labelKey: 'features.amendments.streetscape.objects.common.properties.deckElevationMeters',
        fieldType: 'number',
        unit: 'm',
        min: 0,
        step: 0.1,
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 30000,
    renderKind: 'stairs',
    toolMode: 'path',
    defaultWidth: 2.4,
    color: '#a8a29e',
  },
  hedge: {
    type: 'hedge',
    labelKey: 'features.amendments.streetscape.objects.hedge.label',
    icon: 'Shrub',
    category: 'greenery',
    geometryKind: 'corridor',
    defaultProperties: { height: 1.2, species: 'hecke' },
    propertySchema: [
      {
        key: 'height',
        labelKey: 'features.amendments.streetscape.objects.common.properties.height',
        fieldType: 'number',
        unit: 'm',
        min: 0.3,
        step: 0.1,
      },
      {
        key: 'species',
        labelKey: 'features.amendments.streetscape.objects.tree.properties.species',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.species,
      },
    ],
    costRule: 'per_meter',
    suggestedUnitCostMinor: 18000,
    renderKind: 'barrier',
    toolMode: 'path',
    defaultWidth: 0.8,
    color: '#4d7c3f',
  },
  construction_area: {
    type: 'construction_area',
    labelKey: 'features.amendments.streetscape.objects.constructionArea.label',
    icon: 'Construction',
    category: 'street',
    geometryKind: 'corridor',
    defaultProperties: { status: 'planned', surface: 'unsealed' },
    propertySchema: [
      {
        key: 'status',
        labelKey: 'features.amendments.streetscape.objects.common.properties.status',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.status,
      },
      {
        key: 'surface',
        labelKey: 'features.amendments.streetscape.objects.common.properties.surface',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.surface,
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 7000,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 6,
    color: '#a16207',
  },
  landuse_context_area: {
    type: 'landuse_context_area',
    labelKey: 'features.amendments.streetscape.objects.landuseContextArea.label',
    icon: 'Layers',
    category: 'building',
    geometryKind: 'corridor',
    defaultProperties: { landuseType: 'commercial', influenceBuildings: true },
    propertySchema: [
      {
        key: 'landuseType',
        labelKey:
          'features.amendments.streetscape.objects.landuseContextArea.properties.landuseType',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.landuseType,
      },
      {
        key: 'influenceBuildings',
        labelKey:
          'features.amendments.streetscape.objects.landuseContextArea.properties.influenceBuildings',
        fieldType: 'boolean',
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 500,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 10,
    color: '#b8a083',
  },
  civic_area: {
    type: 'civic_area',
    labelKey: 'features.amendments.streetscape.objects.civicArea.label',
    icon: 'Building2',
    category: 'building',
    geometryKind: 'corridor',
    defaultProperties: { civicType: 'school', publicAccess: true },
    propertySchema: [
      {
        key: 'civicType',
        labelKey: 'features.amendments.streetscape.objects.civicArea.properties.civicType',
        fieldType: 'combobox',
        options: streetDesignPropertyOptions.civicType,
      },
      {
        key: 'publicAccess',
        labelKey: 'features.amendments.streetscape.objects.common.properties.publicAccess',
        fieldType: 'boolean',
      },
    ],
    costRule: 'per_square_meter',
    suggestedUnitCostMinor: 1200,
    renderKind: 'surface',
    toolMode: 'path',
    defaultWidth: 10,
    color: '#90a887',
  },
} satisfies Record<StreetDesignObjectType, StreetDesignObjectDefinition>;

export const streetDesignObjectTypes = Object.keys(
  streetDesignObjectRegistry
) as StreetDesignObjectType[];

export function getStreetDesignObjectDefinition(
  type: StreetDesignObjectType
): StreetDesignObjectDefinition {
  return streetDesignObjectRegistry[type];
}
