  create table "public"."newsletter_subscription" (
    "user_id" uuid not null,
    "email" text not null,
    "subscribed" boolean not null default true,
    "sync_status" text not null default 'pending'::text,
    "resend_contact_id" text,
    "subscription_source" text not null default 'automatic_signup'::text,
    "subscribed_at" timestamp with time zone not null default now(),
    "unsubscribed_at" timestamp with time zone,
    "last_synced_at" timestamp with time zone,
    "last_error" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."newsletter_subscription" enable row level security;


  create table "public"."newsletter_sync_outbox" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid,
    "operation" text not null,
    "email" text not null,
    "previous_email" text,
    "resend_contact_id" text,
    "subscribed" boolean not null default true,
    "status" text not null default 'pending'::text,
    "attempt_count" integer not null default 0,
    "available_at" timestamp with time zone not null default now(),
    "locked_at" timestamp with time zone,
    "completed_at" timestamp with time zone,
    "last_error" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."newsletter_sync_outbox" enable row level security;


  create table "public"."resend_webhook_event" (
    "svix_id" text not null,
    "event_type" text not null,
    "event_created_at" timestamp with time zone,
    "payload" jsonb not null,
    "processed_at" timestamp with time zone not null default now()
      );


alter table "public"."resend_webhook_event" enable row level security;

CREATE UNIQUE INDEX newsletter_subscription_email_key ON public.newsletter_subscription USING btree (lower(email));

CREATE UNIQUE INDEX newsletter_subscription_pkey ON public.newsletter_subscription USING btree (user_id);

CREATE UNIQUE INDEX newsletter_subscription_resend_contact_id_key ON public.newsletter_subscription USING btree (resend_contact_id);

CREATE INDEX newsletter_sync_outbox_pending_idx ON public.newsletter_sync_outbox USING btree (available_at, id) WHERE (status = ANY (ARRAY['pending'::text, 'failed'::text]));

CREATE UNIQUE INDEX newsletter_sync_outbox_pkey ON public.newsletter_sync_outbox USING btree (id);

CREATE UNIQUE INDEX resend_webhook_event_pkey ON public.resend_webhook_event USING btree (svix_id);

alter table "public"."newsletter_subscription" add constraint "newsletter_subscription_pkey" PRIMARY KEY using index "newsletter_subscription_pkey";

alter table "public"."newsletter_sync_outbox" add constraint "newsletter_sync_outbox_pkey" PRIMARY KEY using index "newsletter_sync_outbox_pkey";

alter table "public"."resend_webhook_event" add constraint "resend_webhook_event_pkey" PRIMARY KEY using index "resend_webhook_event_pkey";

alter table "public"."newsletter_subscription" add constraint "newsletter_subscription_resend_contact_id_key" UNIQUE using index "newsletter_subscription_resend_contact_id_key";

alter table "public"."newsletter_subscription" add constraint "newsletter_subscription_sync_status_check" CHECK ((sync_status = ANY (ARRAY['pending'::text, 'synced'::text, 'unsubscribed'::text, 'error'::text, 'deleted'::text]))) not valid;

alter table "public"."newsletter_subscription" validate constraint "newsletter_subscription_sync_status_check";

alter table "public"."newsletter_subscription" add constraint "newsletter_subscription_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."newsletter_subscription" validate constraint "newsletter_subscription_user_id_fkey";

alter table "public"."newsletter_sync_outbox" add constraint "newsletter_sync_outbox_operation_check" CHECK ((operation = ANY (ARRAY['upsert'::text, 'replace_email'::text, 'delete'::text]))) not valid;

alter table "public"."newsletter_sync_outbox" validate constraint "newsletter_sync_outbox_operation_check";

alter table "public"."newsletter_sync_outbox" add constraint "newsletter_sync_outbox_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text]))) not valid;

alter table "public"."newsletter_sync_outbox" validate constraint "newsletter_sync_outbox_status_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.claim_newsletter_sync_jobs(job_limit integer DEFAULT 100)
 RETURNS SETOF public.newsletter_sync_outbox
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
  WITH candidates AS (
    SELECT id
    FROM public.newsletter_sync_outbox
    WHERE (
      status IN ('pending', 'failed') AND available_at <= now()
    ) OR (
      status = 'processing' AND locked_at < now() - INTERVAL '10 minutes'
    )
    ORDER BY id
    FOR UPDATE SKIP LOCKED
    LIMIT least(greatest(job_limit, 1), 100)
  )
  UPDATE public.newsletter_sync_outbox AS job
    SET status = 'processing',
        attempt_count = job.attempt_count + 1,
        locked_at = now(),
        updated_at = now()
    FROM candidates
    WHERE job.id = candidates.id
    RETURNING job.*;
$function$
;

CREATE OR REPLACE FUNCTION public.enqueue_newsletter_subscription(target_user_id uuid, target_email text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  current_subscription public.newsletter_subscription%ROWTYPE;
BEGIN
  INSERT INTO public.newsletter_subscription (user_id, email)
  VALUES (target_user_id, target_email)
  ON CONFLICT (user_id) DO UPDATE
    SET email = excluded.email,
        updated_at = now()
  RETURNING * INTO current_subscription;

  INSERT INTO public.newsletter_sync_outbox (
    user_id,
    operation,
    email,
    resend_contact_id,
    subscribed
  ) VALUES (
    target_user_id,
    'upsert',
    target_email,
    current_subscription.resend_contact_id,
    current_subscription.subscribed
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_auth_user_newsletter_change()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  current_subscription public.newsletter_subscription%ROWTYPE;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.email IS NOT NULL AND NEW.email_confirmed_at IS NOT NULL THEN
      PERFORM public.enqueue_newsletter_subscription(NEW.id, NEW.email);
    END IF;
    RETURN NEW;
  END IF;

  IF OLD.email_confirmed_at IS NULL
    AND NEW.email_confirmed_at IS NOT NULL
    AND NEW.email IS NOT NULL THEN
    PERFORM public.enqueue_newsletter_subscription(NEW.id, NEW.email);
    RETURN NEW;
  END IF;

  IF NEW.email_confirmed_at IS NOT NULL
    AND NEW.email IS NOT NULL
    AND NEW.email IS DISTINCT FROM OLD.email THEN
    SELECT * INTO current_subscription
      FROM public.newsletter_subscription
      WHERE user_id = NEW.id;

    IF FOUND THEN
      UPDATE public.newsletter_subscription
        SET email = NEW.email,
            resend_contact_id = NULL,
            sync_status = 'pending',
            last_error = NULL,
            updated_at = now()
        WHERE user_id = NEW.id;

      INSERT INTO public.newsletter_sync_outbox (
        user_id,
        operation,
        email,
        previous_email,
        resend_contact_id,
        subscribed
      ) VALUES (
        NEW.id,
        'replace_email',
        NEW.email,
        OLD.email,
        current_subscription.resend_contact_id,
        current_subscription.subscribed
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_auth_user_newsletter_delete()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  current_subscription public.newsletter_subscription%ROWTYPE;
BEGIN
  SELECT * INTO current_subscription
    FROM public.newsletter_subscription
    WHERE user_id = OLD.id;

  IF FOUND THEN
    INSERT INTO public.newsletter_sync_outbox (
      user_id,
      operation,
      email,
      resend_contact_id,
      subscribed
    ) VALUES (
      OLD.id,
      'delete',
      current_subscription.email,
      current_subscription.resend_contact_id,
      current_subscription.subscribed
    );
  END IF;

  RETURN OLD;
END;
$function$
;

grant delete on table "public"."newsletter_subscription" to "service_role";

grant insert on table "public"."newsletter_subscription" to "service_role";

grant references on table "public"."newsletter_subscription" to "service_role";

grant select on table "public"."newsletter_subscription" to "service_role";

grant trigger on table "public"."newsletter_subscription" to "service_role";

grant truncate on table "public"."newsletter_subscription" to "service_role";

grant update on table "public"."newsletter_subscription" to "service_role";

grant delete on table "public"."newsletter_sync_outbox" to "service_role";

grant insert on table "public"."newsletter_sync_outbox" to "service_role";

grant references on table "public"."newsletter_sync_outbox" to "service_role";

grant select on table "public"."newsletter_sync_outbox" to "service_role";

grant trigger on table "public"."newsletter_sync_outbox" to "service_role";

grant truncate on table "public"."newsletter_sync_outbox" to "service_role";

grant update on table "public"."newsletter_sync_outbox" to "service_role";

grant delete on table "public"."resend_webhook_event" to "service_role";

grant insert on table "public"."resend_webhook_event" to "service_role";

grant references on table "public"."resend_webhook_event" to "service_role";

grant select on table "public"."resend_webhook_event" to "service_role";

grant trigger on table "public"."resend_webhook_event" to "service_role";

grant truncate on table "public"."resend_webhook_event" to "service_role";

grant update on table "public"."resend_webhook_event" to "service_role";

revoke all on table "public"."newsletter_subscription" from "anon", "authenticated";

revoke all on table "public"."newsletter_sync_outbox" from "anon", "authenticated";

revoke all on table "public"."resend_webhook_event" from "anon", "authenticated";

grant usage, select on sequence "public"."newsletter_sync_outbox_id_seq" to "service_role";

revoke all on function public.enqueue_newsletter_subscription(uuid, text) from public;

revoke all on function public.handle_auth_user_newsletter_change() from public;

revoke all on function public.handle_auth_user_newsletter_delete() from public;

revoke all on function public.claim_newsletter_sync_jobs(integer) from public;

grant execute on function public.claim_newsletter_sync_jobs(integer) to service_role;

CREATE TRIGGER on_auth_user_newsletter_changed AFTER INSERT OR UPDATE OF email, email_confirmed_at ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_auth_user_newsletter_change();

CREATE TRIGGER on_auth_user_newsletter_deleted BEFORE DELETE ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_auth_user_newsletter_delete();
